---

# deploy postgresql
- name: check if postgresql is deployed
  shell: "{{ openshift_cli }} get dc {{ postgresql_service_name }} -n {{ ocp_project }}"
  register: postgresql_deployed
  ignore_errors: true
  changed_when: false

- import_tasks: deploy_postgresql.yml
  when: postgresql_deployed is failed