---

- name: Deploy PostgreSQL database for dispatch service
  hosts: localhost
  connection: local
  gather_facts: false
  run_once: true
  vars_files:
    - group_vars/services.yml

  tasks:
    - import_role:
        name: openshift_dispatch_service_postgresql
      vars:
        ocp_project: "{{ project_services }}"
        ocp_project_display_name: "{{ project_services_name }}"
        ocp_project_desc: "{{ project_services_desc }}"
        resources_dir: "{{ ocp_dir }}/dispatch-service-postgresql"
        playbook_work_dir: "{{ work_dir }}/dispatch-service-postgresql"